AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API using SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs14.x
    Timeout: 5
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get
      CodeUri: s3://varunraj-sam/6a22034951ea215d5a258d8888d16246
  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: put
      CodeUri: s3://varunraj-sam/6a22034951ea215d5a258d8888d16246
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: delete
      CodeUri: s3://varunraj-sam/6a22034951ea215d5a258d8888d16246
